//类头文件 
// Class automatically generated by Dev-C++ New Class wizard
#include <iostream>
#ifndef MYSTRING_H
#define MYSTRING_H
using namespace std;
class mystring
{
    char* a;
    public:
		mystring(char* const);
		~mystring();
	char* returner();
	char* operator+(mystring&); //重载“+”运算符 ，作为strcat函数 
    void operator=(char* const j);//重载“=”运算符，用来向mystring类中的私有成员a传值； 
    void operator=(mystring& );//重载 “=”运算符，作为strcpy函数 
    friend int mystrlen(mystring& );//mystrlen函数 ，和标准strlen函数功能相似 
    friend void mystrlwr(mystring& );//mystrlwt函数，和标准strlwt函数功能相似 
    friend void mystrupt(mystring& );//mystrupt函数，和标准strupt函数功能相似  
    friend void mystrncpy(mystring& ,mystring& ,int );//mystrncpy函数，和标准strncpy函数功能相似  
    friend void mystrncat(mystring& ,mystring& ,int );  //mystrncat 函数，和标准strncat函数功能相似 
    friend void checkstring(mystring& );//异常处理函数 
};
 ostream& operator<< (ostream& ,mystring& );//重载的“<<”运算符 
 
 
#endif // MYSTRING_H
