//类实现文件 
// Class automatically generated by Dev-C++ New Class wizard
#include <iostream>
#include "mystring.h" // class's header file
using namespace std;

ostream& operator<<(ostream& os, mystring& m){
         return os<<m.returner();}

mystring::mystring(char* const str):a(str)
{                 
}

mystring::~mystring()
{
}
char* mystring::returner(){ return a;}
char* mystring::operator+(mystring& s2){
      char* b=a; char* c=s2.a;
      char* f=a; char* g=s2.a;
      int i=0;int j=1;
      while(*b++) i++;
      while(*c++) j++;
      char* d=new char[i+j];
      char* e=d;
      for(int x=0;x<i;x++)
      (*d++)=(*f++);
      for(x=0;x<j;x++)
      (*d++)=(*g++);
      delete d; 
      return e;
      }
void mystring::operator=(char* const str){ 
     char* b=str;
     int i=1;
     while ((*b++))
     i++;
     char* c=new char[i];
     a=c;
     char* d=str;
     while ((*c++)=(*d++));
     delete c;
     }
void mystring::operator=(mystring & str){
     char* b=str.a;
     int i=1;
     while ((*b++))
     i++;
     char* c=new char[i];
     a=c;
     char* d=str.a;
     while ((*c++)=(*d++));
     delete c;
     }
int mystrlen(mystring& str){
    char* b=str.a;
    int i=0;
    while ((*b++))
    i++;
    return i;
}
void mystrlwr(mystring& str){
     char* b=str.a;
     char* c=str.a;
     while (*b){
     if((*b>64)&(*b<91)){
                        *b=*b+32;
                          b++;}
                         else  b++;
     }
     cout<<c<<endl;
}
void mystrupt(mystring& str){
     char* b=str.a; 
     char* c=str.a;
     while (*b){
     if((*b>89)&(*b<123)){
                         *b=*b-32;
                          b++;}
                          else b++;
     }
     cout<<c<<endl;
}                     
void mystrncpy(mystring& str1,mystring& str2,int n){
    
     char* y=str2.a;
     str1.a=new char[n+1];
     char* h=str1.a;
     for(int i=0;i<n;i++,h++,y++)
     *h=*y;
     *h=0;
     cout<<str1.a<<endl;
     delete str1.a;
}
void mystrncat(mystring& str1,mystring& str2,int n){
     char* h=str1.a;char* k=str1.a;char* y=str2.a;
     int i=0;
     while(*h++)
                  i++;
     char* m=new char[i+n+1];
     char* f=m;
     str1.a=f;
     for(int j=0;j<i;j++){
             *m=*k ; m++;k++;}
     for(j=0;j<n;j++){
             *m=*y; m++;y++;}
     *m=0;
     cout<<str1.a<<endl;
     delete m;
     }
void checkstring(mystring& str){
     int i=mystrlen(str) ;
     if(i>0&&i<=10){}
     else {
          cout<<"数组越界!输入的数组长度小于10!"<<endl;
          delete str.a;
          throw 1;  //抛出异常 
          }
}  
         
     
     
     
     
     
     
     
     
     
     
     
     
